spring:
  profiles:
          active: "@spring.profiles.active@"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
    
logging:
  level: 
    root: info
  file: consumer.log
