spring:
  profiles:
          active: "@spring.profiles.active@"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
    
server:
  port: 8081
  context-path: /
    
logging:
  level: 
    root: info
  file: producer.log

  